apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-devops
  template:
    metadata:
      labels:
        app: todo-devops
    spec:
      containers:
        - name: todo-devops
          image: yassine0707/todo-devops
          ports:
            - containerPort: 80

